version: '3'
networks:
    app-tier:
      driver: bridge
services:
    app:
        build: .
        ports:
            - "8383:8383"
            - "9192:9192"
        networks:
            - app-tier